stages:
- stage: Test
  jobs:
  - job: TestJob
    displayName: 'Run Tests'
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        version: '3.x'
        includePreviewVersions: true

    - task: DotNetCoreCLI@2
      displayName: 'Restore dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: '**/*Test.csproj'
        arguments: '--configuration Release'
